### ISSUE TITLE
Interrupt 정리

### ISSUE THREAD

**Issue by insub2004** [1004s/fbp-docs#20]
## 1. volatile boolean runFlag를 사용

```java
public class ThreadStopMainV1 {

    public static void main(String[] args) {
        Thread thread = new Thread(new MyTask(), "work");

        thread.start();
        sleep(2000);
        log("main -> work 작업 종료 지시");
        MyTask.runFlag = true;
        log("main 종료");
    }

    static class MyTask implements Runnable {

        static volatile boolean runFlag = false;

        @Override
        public void run() {
            while(!runFlag) {
                log("작업 중");
                sleep(3000);
            }
            log("작업 완료");
            log("자원 정리");
        }
    }

}

```

1번 문제점

- runFlag가 바뀌고 sleep(3000)이 끝나고 while조건을 읽는 동안의 Gap동안에는 끝나지 않음

## 2. 인터럽트를 사용하면 `WATING` , `TIMED_WATING` 같은 대기 상태의 스레드를 직접 깨워 → 작동하는 `RUNNABLE` 상태로 만들 수 있다.

```java
public class ThreadStopMainV2 {

    public static void main(String[] args) {
        MyTask task = new MyTask();
        Thread thread = new Thread(task, "work");
        thread.start();

        sleep(4000);
        log("작업 중단 지시 thread.interrupt()");
        thread.interrupt();
        log("work 스레드 인터업트 상태1 = " + thread.isInterrupted());
    }

    static class MyTask implements Runnable {

        @Override
        public void run() {

            try {
                while (true) {
                    log("작업 중");
                    Thread.sleep(3000);
                }
            } catch (InterruptedException e) {
                log("work 스레드 인터럽트 상태 2 = " + Thread.currentThread().isInterrupted());
                log("interrupt message = " +e.getMessage());
                log("state = " + Thread.currentThread().getState());
            }

            log("자원 정리");
            log("자원 종료");
        }
    }
}

15:07:58.811 [     work] 작업 중
15:08:01.818 [     work] 작업 중
15:08:02.798 [     main] 작업 중단 지시 thread.interrupt()
15:08:02.809 [     main] work 스레드 인터업트 상태1 = true
15:08:02.809 [     work] work 스레드 인터럽트 상태 2 = false
15:08:02.812 [     work] interrupt message = sleep interrupted
15:08:02.812 [     work] state = RUNNABLE
15:08:02.813 [     work] 자원 정리
15:08:02.815 [     work] 자원 종료
```

- main 스레드에서 work 스레드를 interrupt()를 호출한 이후
- work 스레드가 sleep(3000)메서드를 실행중이여서 `TIMED_WATING` 상태였는데 깨어남
    - catch()문에 InterruptedException에 걸려서 while문을 빠져 나온다.
    - 동시에 interrupt 상태 boolean을 false로 초기화한다.

### 중요

> 참고 

interrupt를 호출했다고 해서 즉각 InterruptedException이 발생하는게 아니다!!!!
실행 중인 스레드에 interrupt()를 호출하면, 단순히 interrupt 상태만 변경됩니다!!!!!

그런데 interrupt당한 상태의 스레드가! sleep()과 같은 InterruptedException을 발생시키는 코드를 만나거나, 중이면 catch문을 통해서 `WATING`, `TIMED_WATING` 과 같은 상태에서 → `RUNNABLE` 상태가 됨
> 

**예외 처리 메커니즘**

- 스레드가 위의 상태나 메서드 호출 시점에 도달하면, JVM은 interrupt 상태를 확인합니다.
- interrupt 상태가 true이면 InterruptedException을 발생시키고, interrupt 상태를 false로 초기화합니다.

![image.png](https://prod-files-secure.s3.us-west-2.amazonaws.com/2abae315-467d-42b5-b06f-150ea4df8098/9b2445da-6485-43c0-8477-603a22900ee0/add94c12-1bc6-4ff5-b4f1-90b39e698f14.png)

- InterruptedException이 발생했을 때 2가지 일이 발생
    - work스레드는 `TIMED_WATING` 상태에서 `RUNNABLE` 상태로 변경되고 InterruptedException예외를 처리하면서 반복문을 탈출
    - 인터럽트 상태에서 인터럽트 예외가 발생하면 work스레드는 다시 작동하는 상태가 된다. 따라서 work스레드의 인터럽트 상태는 종료된다.
        - work스레드의 인터럽트 상태는 false로 변경된다.

- sleep(3000)을 걸었다고 interrupt상태가 true 된게 아니고 state가 `TIMED_WATING` 가 변경된 것 뿐
- workThread.interrupt() 와 같이 interrupt 상태를 true로 바꿔줘야 인터럽트 상태이다.

2번 문제점

while(true)부분에서 인터럽트 체크를 하지 않아서 sleep(3000)인 부분에서만 인터럽트 반응을 한다.

while 조건문에서 인터럽트 상태를 확인하도록 코드를 변경해보자.

## 3. while 조건문 변경 Thread.isInterrupted()

```java
public class ThreadStopMainV3 {

    public static void main(String[] args) {
        MyTask task = new MyTask();
        Thread thread = new Thread(task, "work");
        thread.start();

        sleep(100);
        log("작업 중단 지시 thread.interrupt()");
        thread.interrupt();
        log("work 스레드 인터업트 상태1 = " + thread.isInterrupted());
    }

    static class MyTask implements Runnable {

        @Override
        public void run() {

            while (!Thread.currentThread().isInterrupted()) { // 상태만 확인, 변경은 안함
                log("작업중");
            }

            log("work 스레드 인터럽트 상태 2 = " + Thread.currentThread().isInterrupted());

            log("자원 정리");
            log("자원 종료");
        }
    }
}

....
15:24:26.261 [     work] 작업중
15:24:26.261 [     work] 작업중
15:24:26.261 [     work] 작업중
15:24:26.261 [     work] 작업중
15:24:26.261 [     work] 작업중
15:24:26.261 [     work] 작업중
15:24:26.261 [     work] 작업중
15:24:26.261 [     work] 작업중
15:24:26.261 [     work] 작업중
15:24:26.261 [     main] 작업 중단 지시 thread.interrupt()
15:24:26.261 [     work] 작업중
15:24:26.261 [     work] 작업중
15:24:26.265 [     main] work 스레드 인터업트 상태1 = true
15:24:26.265 [     work] work 스레드 인터럽트 상태 2 = true
15:24:26.265 [     work] 자원 정리
15:24:26.265 [     work] 자원 종료
```

> 참고 : isInterrupted() 메서드는 인터럽트 상태만 확인할 뿐, 직접 인터럽트 상태를 변경해주지 않는다.
> 
- 자원 종료까지 무사히 마쳤다.
- 그런데 2번에서 “work 스레드 인터럽트 상태 2 = “이 부분을 비교해보자.
    - 2번에서는 false
    - 3번에서는 true
- 그렇다면 3번같은 상황에서 어떤 문제가 발생하는지 3-1번의 예제코드를 확인해보자.

## 3-1. 인터럽트(true) 상태가 `전이` 되었을 때 문제점

```java
public class ThreadStopMainV3_1 {

    public static void main(String[] args) {
        MyTask task = new MyTask();
        Thread thread = new Thread(task, "work");
        thread.start();

        sleep(100);
        log("작업 중단 지시 thread.interrupt()");
        thread.interrupt();
        log("work 스레드 인터업트 상태1 = " + thread.isInterrupted());
    }

    static class MyTask implements Runnable {

        @Override
        public void run() {

            while (!Thread.currentThread().isInterrupted()) { // 상태만 확인, 변경은 안함
                log("작업중");
            }

            log("work 스레드 인터럽트 상태 2 = " + Thread.currentThread().isInterrupted());

            try {
                log("자원 정리 시도");
                Thread.sleep(1000);
                log("자원 정리 완료");
            } catch (InterruptedException e) {
                log("자원 정리 완료 실패 - 자원 정리 중 인터럽트 발생"); 
                log("work 스레드 인터럽트 상태3 = " +
                        Thread.currentThread().isInterrupted());
            }
            log("작업 종료 >>> '자원 정리 완료' 로그가 떴는지 체크");
        }
    }
}

...
15:32:39.402 [     work] 작업중
15:32:39.402 [     work] 작업중
15:32:39.403 [     work] 작업중
15:32:39.403 [     work] 작업중
15:32:39.403 [     work] 작업중
15:32:39.402 [     main] 작업 중단 지시 thread.interrupt()
15:32:39.403 [     work] 작업중
15:32:39.406 [     main] work 스레드 인터업트 상태1 = true
15:32:39.406 [     work] work 스레드 인터럽트 상태 2 = true
15:32:39.406 [     work] 자원 정리 시도
**15:32:39.406 [     work] 자원 정리 완료 실패 - 자원 정리 중 인터럽트 발생 <<<<<<<**
15:32:39.406 [     work] work 스레드 인터럽트 상태3 = false
15:32:39.406 [     work] 작업 종료 >>> '자원 정리 완료' 로그가 떴는지 체크

```

- 결과 화면에서 <<<<< 표시 부분을 보고 생각해보자.
- “work 스레드 인터럽트 상태 2” 상태를 보면 true다.
    - 즉, 인터럽트가 발생해서 while문을 빠져나왔다.
    - 하지만 catch문 처럼 InterruptException이 발생한 상황이 아니라서 2번의 예제처럼 인터럽트 상태를 false로 바꿔주진 못했다.
- 자원 정리하려는 try-catch문에 접근했다.
- 그러나 “자원 정리 로직” 전에 인터럽트(true) 상태가 “자원 정리 로직” 실행하는 상황까지 `전이` 가 되어 버렸다.
- 그래서 의도하지 않은 InterruptedException이 발생했다!
    - **자원 정리 완료 실패 - 자원 정리 중 인터럽트 발생 <<<<<<<**
- catch문을 통해 InterruptedException을 처리했기 때문에 “work 스레드 인터럽트 상태3”는 false다.

결국 우리가 기대했던 결과가 아니다! 

“작업중 처리 로직”(while문)을 빠져나오기 위해서 interrupt를 발생 시켜서 while문을 빠져 나왔지만

`인터럽트 상태` 를 바꿔주지 않아서 의도치 않게 “자원 정리 로직”(try-catch)에서 InterruptException이 발생해 자원 정리를 끝내지 못하고 work스레드가 종료되었다.

> 다시 말하지만 isInterrupted() 메소드는 인터럽트 상태를 반환만 해줄 뿐, 변경은 해주지 않는다.
> 

결국 **스레드의 인터럽트 상태를 정상으로 돌리지 않으면 이후에도 계속 인터럽트가 발생한다!!!**

## 4. Thread.interrupted()를 사용하자!

단순히 스레드의 인터럽트 상태를 확인할 땐 `Thread.isInterrupted()` 를 사용해도 좋지만

직접 체크해서 사용하려면 `Thread.interrupted()` 를 사용하자!

`Thread.interrupted()` 는 다음과 같이 동작한다.

- 스레드의 인터럽트 상태라면 true를 반환하고, 인터럽트 상태를 false로  변경
- 스레드의 인터럽트 상태가 아니라면 false를 반환하고, 인터럽트 상태를 변경하지 않는다.

```java
public class ThreadStopMainV4 {

    public static void main(String[] args) {
        MyTask task = new MyTask();
        Thread thread = new Thread(task, "work");
        thread.start();

        sleep(100);
        log("작업 중단 지시 thread.interrupt()");
        thread.interrupt();
        log("work 스레드 인터업트 상태1 = " + thread.isInterrupted());
    }

    static class MyTask implements Runnable {

        @Override
        public void run() {

            while (!Thread.interrupted()) { // 상태만 확인, 변경도 해줌
                log("작업중");
            }

            log("work 스레드 인터럽트 상태 2 = " + Thread.currentThread().isInterrupted());

            try {
                log("자원 정리 시도");
                Thread.sleep(1000);
                log("자원 정리 완료");
            } catch (InterruptedException e) {
                log("자원 정리 완료 실패 - 자원 정리 중 인터럽트 발생"); 
                log("work 스레드 인터럽트 상태3 = " +
                        Thread.currentThread().isInterrupted());
            }
            log("작업 종료 >>> '자원 정리 완료' 로그가 떴는지 체크");
        }
    }
}

...
16:05:48.869 [     work] 작업중
16:05:48.869 [     work] 작업중
16:05:48.869 [     work] 작업중
16:05:48.869 [     main] 작업 중단 지시 thread.interrupt()
16:05:48.869 [     main] work 스레드 인터업트 상태1 = true
16:05:48.870 [     work] 작업중
**16:05:48.873 [     work] work 스레드 인터럽트 상태 2 = false <<<<<<<<<<<<<<**
16:05:48.873 [     work] 자원 정리 시도
**16:05:49.877 [     work] 자원 정리 완료 <<<<<<<<<<<<**
16:05:49.877 [     work] 작업 종료 >>> '자원 정리 완료' 로그가 떴는지 체크
```

자, 결과에서 <<<<<<<< 표시를 잘 보자.

앞에서 일어났던 **인터럽트 상태 전이 문제**가 해결되었다.

## 결론

인터럽트의 목적을 달성하면 인터럽트 상태를 다시 정상으로 돌려놓자!!

---

### 결국 인터럽트 상태를 확인하고 되돌릴 수 있는 방법 2가지

1. try-catch를 이용해 InterruptedException 처리
2. Thread.interrupted(); 메서드 사용

### try - catch은 어떻게 인터럽트 상태를 바꿔주지???

- InterruptedException이 catch 블록에서 잡히면, JVM은 자동으로 해당 스레드의 interrupt 상태를 false로 초기화한다.
- 즉, 실제로 interrupt 상태를 변경하는 코드는 JVM 내부에 구현되어 있습니다. → 우리가 볼 수 없다 ㅋㅋ

### Object.wait(), sleep(), join()에서 InterruptException이 발생한다고 하는데 wait() 메소드의 경우에 notify()나 notifyAll()메서드만 사용해야되는거 아니였어??

- 아니다. 둘의 사용 목적이 다르다고 생각하면 된다.
- 먼저 notify()나 notifyAll()을 사용하는건 “스레드 대기 집합”에 있는 “스레드의 상태”를 변경이 목적
    - `WAITING` → `BOLCKED` 상태로 변경해서 Lock 경쟁에 참여할 수 있게 함
    - 정상적인 비즈니스 로직의 일부
    - 조건이 충족되어 스레드가 계속 진행해도 된다는 신호
    - 예: 데이터가 준비됨, 자원이 사용 가능해짐
- interrupt()메서드는 별도의 로직 처리가 목적
    - 비정상적인 상황 처리
    - 스레드의 강제 종료
    - 타임아웃 처리
    - 긴급 상황 대응

핵심적인 차이는

- notify/notifyAll: "이제 계속 진행해도 됩니다"
- interrupt: "현재 작업을 중단하고 다른 처리를 해야 합니다"

**Comment by caboooom** [comment]
# 잘 정리해주셔서 정말 감사합니다 도움이 많이 되었읍니다
